---
- hosts: prometheus
  gather_facts: no
  become: yes
  tasks:
  - name: Waiting for ssh
    wait_for_connection:
      timeout: 400

  - name: Updating apt
    apt:
      update_cache: yes
      upgrade: yes

 - name: Creating filesystems
    filesystem:
      fstype: xfs
      dev: {{ item }}
    with_item:
      - /dev/sdb

- name: Mounting pgsrc filesystem
    mount:
      path: /promdata
      src: /dev/sdb
      opts: nofail,noatime,nodev,defaults
      state: mounted