---
- hosts: prometheus
  vars:
    prometheus_version: 2.22.0
  gather_facts: no
  become: yes
  tasks:
  - name: Waiting for ssh
    wait_for_connection:
      timeout: 400

  - name: Updating apt
    apt:
      update_cache: yes
      upgrade: yes

  - name: Installing packages
    apt:
      pkg:
        - wget
        - curl
        - vim
      state: present
      update_cache: yes

  - name: Creating filesystems
    filesystem:
      fstype: xfs
      dev: "{{ item }}"
    with_items:
      - /dev/sdb

  - name: Mounting pgsrc filesystem
    mount:
      path: /promdata
      src: /dev/sdb
      fstype: xfs
      opts: nofail,noatime,nodev,defaults
      state: mounted

  - name: Adding system group prometheus
    group:
      name: prometheus
      state: present
      system: yes

  - name: Adding system user prometheus
    user: 
      name: prometheus
      shell: /bin/false
      group: prometheus
      system: yes

  - name: Setting up prometheus directories
    file:
      path: "{{ item }}"
      state: directory
      owner: prometheus
      group: prometheus
      recurse: yes
    with_items:
      - /etc/prometheus/rules
      - /etc/prometheus/rules.d
      - /etc/prometheus/files_sd
      - /var/lib/prometheus

  - name: Downloading prometheus
    unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
      dest: /tmp
      remote_src: yes

  - name: Copying binaries
    copy:
      src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
      dest: "/usr/local/bin/"
      owner: prometheus
      group: prometheus
      mode: 0750
      remote_src: yes
    with_items:
      - promtool
      - prometheus

  - name: Copying configs
    copy:
      src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
      dest: /etc/prometheus/
      owner: prometheus
      group: prometheus
      remote_src: yes
    with_items:
      - console_libraries
      - consoles
      - prometheus.yml

  - name: Deleting tmp folder
    file:
      path: '/tmp/prometheus-{{ prometheus_version }}.linux-amd64'
      state: absent

  - name: Setting up prometheus systemd
    copy:
      src: files/prometheus.service
      dest: /etc/systemd/system
      owner: root
      group: root
  
  - name: Refreshing systemd
    systemd: daemon_reload=yes

  - name: Enabling and starting prometheus service
    systemd:
      name: prometheus.service
      state: started
      enabled: yes
